$files = @(
"C:\Users\sasch\henoch\HENOCH-Exeget\22.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\23.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\24.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\25.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\26.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\27.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\28.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\29.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\30.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\31.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\32.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\33.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\34.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\35.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\36.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\37.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\38.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\39.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\40.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\41.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\42.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\43.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\44.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\45.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\46.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\47.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\48.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\49.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\50.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\51.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\52.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\53.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\54.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\55.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\56.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\57.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\58.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\59.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\60.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\61.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\62.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\63.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\64.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\65.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\66.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\67.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\68.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\69.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\70.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\71.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\72.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\73.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\74.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\75.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\76.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\77.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\78.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\79.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\80.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\81.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\82.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\83.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\84.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\85.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\86.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\87.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\88.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\89.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\89_2.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\90.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\91.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\92.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\93.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\94.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\95.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\96.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\97.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\98.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\99.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\100.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\101.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\102.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\103.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\104.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\105.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\106.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\107.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\108.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\1.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\2.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\3.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\4.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\5.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\6.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\7.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\8.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\9.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\10.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\11.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\12.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\13.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\14.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\15.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\16.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\17.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\18.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\19.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\20.txt"
"C:\Users\sasch\henoch\HENOCH-Exeget\21.txt"
)

$outFile = "C:\Users\sasch\henoch\HENOCH-Exeget\ALL_CLEAN.txt"

# Regex: entfernt am Zeilenanfang "9:1", "10:12" etc. inkl. Leerzeichen dahinter
$pattern = '^\s*\d+\s*:\s*\d+\s+'

# Start: leere Ausgabedatei
"" | Out-File -FilePath $outFile -Encoding UTF8

foreach ($f in $files) {
  if (Test-Path $f) {
    Get-Content -LiteralPath $f -Encoding UTF8 | ForEach-Object {
      $_ -replace $pattern, ''
    } | Out-File -FilePath $outFile -Encoding UTF8 -Append
    "" | Out-File -FilePath $outFile -Encoding UTF8 -Append   # Leerzeile zwischen Dateien (optional)
  } else {
    Write-Host "FEHLT: $f"
  }
}

Write-Host "Fertig: $outFile"
